advito-main/advito/urls.py
from django.conf.urls import url
from advito import views
from django.urls import path, reverse_lazy
from django.views.generic import TemplateView
from advito.views import SignupView, LoginView, EditProfileView, ProfileView, logout_view, PeopleView, EditPostView, DeletePostView
from django.contrib.auth.decorators import login_required



urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    path('all/', views.AllView.as_view(), name='all'),
    path('category/', views.category, name='category'),
    path('post/create/', views.CreatePostView.as_view(), name='post_create'),
    path('post/<int:add_id>/', views.PostView.as_view(), name='post_detail'),
    path('post/<int:add_id>/edit/', views.EditPostView.as_view(), name='post_edit'),
    path('post/<int:add_id>/delete/', views.DeletePostView.as_view(), name='post_delete'),
    path('people/', views.PeopleView.as_view(), name='people'),
    path('category/<int:category_id>/', views.cat_ord, name='categ'),
    path('category/create/', views.categ_create, name='categ_create'),
    path('<int:user_id>/profile/', ProfileView.as_view(), name='profile'),
    path('post/<int:add_id>/delete_success/', TemplateView.as_view(template_name='advito/delete_succes.html'), name='delete-post-success'),

]


from django.contrib.auth.views import PasswordResetDoneView, PasswordResetView, PasswordResetConfirmView, PasswordResetCompleteView

urlpatterns += [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', logout_view, name='logout'),
    path('<int:user_id>/profile/edit', login_required(EditProfileView.as_view()), name='edit-profile'),
    path('signup/', SignupView.as_view(), name='signup'),
    path('password_reset/', PasswordResetView.as_view(success_url=reverse_lazy('users:password_reset_done'),
                                                      template_name='my_auth/password_reset.html'),
         name='password_reset'),

    path('password_reset/done', PasswordResetDoneView.as_view(template_name='my_auth/password_reset_done.html'),
         name='password_reset_done'),

    path('password_reset/<str:uidb64>/<slug:token>', PasswordResetConfirmView.as_view(
        success_url=reverse_lazy('users:password_reset_complete')), name='password_reset_confirm'),

    path('password_reset/complete', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

advito-main/blogproj/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.contrib.staticfiles.urls import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('advito.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

advito-main/advito/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.db.models.signals import post_save
from django.dispatch import receiver



def ava_path(instance, filename):
    return 'user_{0}/avas/{1}'.format(instance.user.id, filename)


def add_path(instance, filename):
    return 'user_{0}/posts/{1}'.format(instance.author.id, filename)


class Profile(models.Model):
    '''
    Модель пользователя
    '''
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='user_profile')
    birth_date = models.DateField('Date of birth', null=True, blank=True)
    about = models.TextField('About', max_length=500, blank=True)
    ava = models.ImageField(upload_to=ava_path, default=None)
    phone_number = models.CharField(max_length=12, default=None)

    def __str__(self):
        return str(self.user.username)


class Category(models.Model):
    name = models.TextField(max_length=64, verbose_name='название')

    def __str__(self):
        return str(self.name)


class Add(models.Model):
    '''
    Объявление
    '''
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    header = models.TextField(max_length=100)
    description = models.TextField(max_length=1000, blank=True)
    image = models.ImageField(upload_to=add_path)
    date_pub = models.DateTimeField(auto_now_add=True)
    date_edit = models.DateTimeField(auto_now=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='категория')

    def __str__(self):
        return 'Author {} date {}'.format(self.author.username, self.date_pub)


# @receiver(post_save, sender=User)
# def create_user_profile(sender, instance, created, **kwargs):
#     if created:
#         Profile.objects.create(user=instance)
#
#
# @receiver(post_save, sender=User)
# def save_user_profile(sender, instance, **kwargs):
#     instance.user_profile.save()


class Comment(models.Model):
    """
    Коментарий к посту
    """
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    text = models.TextField(max_length=700, blank=False)
    in_post = models.ForeignKey(Add, on_delete=models.CASCADE)
    date_publish = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return "{0} : {1}".format(self.author, self.text[:10] + "...")

advito-main/advito/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.utils import timezone
from django.template import loader
from django.utils.decorators import method_decorator
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, View
from .exceptions import PermissionDenied
from .forms import PostForm, CatForm, CommentForm, SignupForm, LoginForm, UpdateProfileForm
from advito.models import Add, Category, Comment, Profile


class IndexView(ListView):
    '''
    вьюха для главной страницы
    '''
    model = Add
    template_name = 'advito/index.html'
    context_object_name = 'posts'

    def get_queryset(self):
        return Add.objects.order_by('-date_pub')[:6]


class AllView(ListView):
    '''
    вьюха для страницы всех объявлений
    '''
    model = Add
    template_name = 'advito/all.html'
    context_object_name = 'posts'

    def get_queryset(self):
        return Add.objects.order_by('-date_pub')


class PostView(DetailView):
    '''
    вьюха для просмотра поста
    '''
    model = Add
    context_object_name = 'post'
    comment_form = CommentForm
    pk_url_kwarg = 'add_id'
    template_name = 'advito/post-detail.html'

    def get(self, request, add_id, *args, **kwargs):
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        context['comments'] = Comment.objects.filter(in_post__id=add_id).order_by('-date_publish')
        context['comment_form'] = None
        if request.user.is_authenticated:
            context['comment_form'] = self.comment_form
        return self.render_to_response(context)

    @method_decorator(login_required)
    def post(self, request, add_id, *args, **kwargs):
        post = get_object_or_404(Add, id=add_id)
        form = self.comment_form(request.POST)
        if form.is_valid():
            comment = form.save()
            comment.author = request.user
            comment.in_post = post
            comment.save()
            comments = post.comment_set.all()
            return render(request, self.template_name, context={
                'comment_form': self.comment_form,
                'post': post,
                'comments': comments.order_by('-date_publish')
            })
        else:
            return render(request, self.template_name, context={
                'comment_form': form,
                'post': post,
                'comments': comments.order_by('-date_publish')
            })


def cat_ord(request, category_id):
    '''
    вьюха для просмотра постов по категориям
    '''
    category = get_object_or_404(Category, id=category_id)
    posts = Add.objects.filter(category=category)
    context = {
        'posts': posts,
    }
    return render(request, 'advito/cat_ord.html', context)



class PeopleView(ListView):
    '''
    вьюха для главной страницы
    '''
    model = Profile
    template_name = 'advito/people.html'
    context_object_name = 'users'

    def get_queryset(self):
        return Profile.objects.all()


class CreatePostView(CreateView):
    '''
    вьха для создания поста
    '''
    form_class = PostForm
    template_name = 'advito/post_create.html'

    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST, request.FILES)
        context = {}

        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            context['post_was_created'] = True
            context['form'] = self.form_class
            return render(request, self.template_name, context)
        else:
            context['post_was_created'] = False
            context['form'] = form
            return render(request, self.template_name, context)


class DeletePostView(DeleteView):
    '''
    вьюха для удаления поста
    '''
    model = Add
    context_object_name = 'post'
    pk_url_kwarg = 'add_id'
    template_name = 'advito/post_delete.html'

    def get_success_url(self):
        add_id = self.kwargs['add_id']
        return reverse('delete-post-success', args=(add_id, ))


def category(request):
    '''
    вьюха для категорий
    '''
    categ_queryset = Category.objects.all()
    template = loader.get_template('advito/cat.html')
    context = {
        'categ': categ_queryset,
    }
    return HttpResponse(template.render(context))


class EditPostView(UpdateView):
    model = Add
    pk_url_kwarg = 'add_id'
    template_name = 'advito/post_edit.html'
    form_class = PostForm

    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        if obj.author != self.request.user:
            raise PermissionDenied("You are not author of this post")
        return super(EditPostView, self).dispatch(request, *args, **kwargs)

    def get_success_url(self):
        add_id = self.kwargs['add_id']
        return reverse('advito:post_detail', args=(add_id, ))


def categ_create(request):
    '''
    вьюха для создания объявления
    '''
    form_cat = CatForm()
    template_name = 'advito/cat_create.html'
    context = {'form_cat': form_cat}
    if request.method == "GET":
        return render(request, template_name, context)
    elif request.method == "POST":
        form_cat = CatForm(request.POST)

        if form_cat.is_valid():
            cat = form_cat.save(commit=False)
            cat.author = request.user
            cat.save()
            context['cat_was_created'] = True
            return render(request, template_name, context)
        else:
            context['cat_was_created'] = False
            context['form_cat'] = form_cat
            return render(request, template_name, context)

    return render(request, 'advito/cat_create.html', {'form_cat': form_cat})


from django.contrib.auth.views import LoginView
from django.contrib.auth import authenticate, login, logout


class LoginView(LoginView):
    template_name = 'my_auth/login.html'
    form_class = LoginForm

    def post(self, request, *args, **kwargs):
        form = self.form_class(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect(reverse('index'), request)
            else:
                context = {}
                context['form'] = form
                return render(request=request, template_name=self.template_name, context=context)
        else:
            context = {'form': form}
            return render(request=request, template_name=self.template_name, context=context)


class ProfileView(DetailView):
    model = Profile
    template_name = 'advito/profile.html'

    def get_object(self):
        return get_object_or_404(Profile, user__id=self.kwargs['user_id'])


@login_required
def logout_view(request):
    logout(request)
    return redirect(reverse("index"))


class SignupView(View):
    template_name = 'my_auth/signup.html'
    registration_form = SignupForm

    def get(self, request, *args, **kwargs):
        context = {'form': self.registration_form}
        return render(request=request, template_name=self.template_name, context=context)

    def post(self, request, *args, **kwargs):
        user_form = SignupForm(data=request.POST)
        registered = False
        if user_form.is_valid():
            user = user_form.save(commit=True)
            user.email = user_form.cleaned_data['email']
            user.save()
            registered = True
            return render(request, 'my_auth/signup.html',
                          {'registered': registered})
        else:
            return render(request, 'my_auth/signup.html',
                          {'form': user_form,
                           'registered': registered})


class EditProfileView(UpdateView):
    model = Profile
    form_class = UpdateProfileForm
    template_name = 'advito/edit_profile.html'
    slug_field = "user_id"
    slug_url_kwarg = "user_id"

    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        if obj.user != self.request.user:
            raise Http404("It is not your profile!")
        return super(EditProfileView, self).dispatch(request, *args, **kwargs)

    def get_success_url(self):
        user_id = self.kwargs['user_id']
        return reverse('profile', args=(user_id,))

advito-main/advito/templates/advito/all.html
{% extends 'advito/layout.html' %}
{% block title %}
    <title>Все посты</title>
{% endblock title %}
{% block unique_content %}
    <p>Все объявления</p>
        <ul class="post-set">
       {% for post in posts %}
           <li class="post-set-block">
               <a href="{% url 'post_detail' post.id %}">
                   <div>
                       <img class="imagi" alt="posts image" src="{{ post.image.url }}"
                            style="height: 250px;">
                   </div>
                   <p>{{ post.author }}</p>
                   <p>{{ post.header }}</p>
                   <p class="data">{{ post.date_pub }}</p>
               </a>
           </li>
           {% endfor %}
    </ul>
{% endblock unique_content %}

advito-main/advito/templates/advito/cat.html
{% extends 'advito/layout.html' %}
{% block title %}
    <title>Категории</title>
{% endblock title %}
{% block unique_content %}
    <p>Категории объявлений</p>
    <ul class="cat-set">
     {% for cat in categ %}
        <li class="cat">
            <a href="{% url 'categ' cat.id %}">{{ cat.name }}</a>
        </li>
     {% endfor %}
    </ul>
    {% if user.is_authenticated %}
        {% if user.id == 2 %}
            <a href="{% url 'categ_create' %}">Создать категорию</a>
        {% endif %}
    {% endif %}
{% endblock unique_content %}

advito-main/advito/templates/advito/cat_create.html
{% extends 'advito/layout.html' %}
{% block unique_content %}
    <form enctype="multipart/form-data" method="post">
        {% csrf_token %}
        {{ form_cat.as_p }}
        <button type="submit">Опубликовать</button>
    </form>
</body>
</html>

advito-main/advito/templates/advito/cat_ord.html
{% extends 'advito/layout.html' %}
{% block title %}
    <title>{{ category.name }}</title>
{% endblock title %}
{% block unique_content %}
{% if posts %}
    <ul class="post-set">
       {% for post in posts %}
           <li class="post-set-block">
               <a href="{% url 'post_detail' post.id %}">
                   <div>
                       <img class="imagi" alt="posts image" src="{{ post.image.url }}"
                            style="height: 250px;">
                   </div>
                   <p>{{ post.author }}</p>
                   <p>{{ post.header }}</p>
                   <p class="data">{{ post.date_pub }}</p>
               </a>
           </li>
           {% endfor %}
    </ul>
    {% else %}
    <p>К сожалению, пока объявлений по данной категории нету:(</p>
{% endif %}
{% endblock unique_content %}

advito-main/advito/templates/advito/delete_succes.html
{% extends 'advito/layout.html' %}
{% block unique_content %}
    <h1 class='msg'> Пост удален </h1>
<h2 class='msg'> <a href='{% url 'index' %}' class='msg'> Вернуться на главную </a> или
<a href='{% url 'post_create' %}' class='msg'> создать новый пост </a> </h2>
{% endblock unique_content %}

advito-main/advito/templates/advito/edit_profile.html
{% extends 'advito/layout.html' %}
{% block unique_content %}
<form method="post" enctype="multipart/form-data">{% csrf_token %}
            {{ form.as_p }}
            {{ field.errors }}
    <button type="submit" class="btn btn-info text-center" > Принять изменения </button>
    </form>
{% endblock unique_content %}

advito-main/advito/templates/advito/index.html
{% extends 'advito/layout.html' %}
{% block unique_content %}
    <p>Всем привет! Добро пожаловать на доску объявлений - advito!</p>
    {% if posts %}
    <ul class="post-set">
       {% for post in posts %}
           <li class="post-set-block">
               <a href="{% url 'post_detail' post.id %}">
                   <div>
                       <img class="imagi" alt="posts image" src="{{ post.image.url }}"
                            style="height: 250px;">
                   </div>
                   <p>{{ post.author }}</p>
                   <p>{{ post.header }}</p>
                   <p class="data">{{ post.date_pub }}</p>
               </a>
           </li>
           {% endfor %}
    </ul>
        <a class="show-all underl" href="{% url 'all' %}">Показать все объявления</a>
    {% endif %}
{% endblock unique_content %}

advito-main/advito/templates/advito/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}
        <title>Advito</title>
    {% endblock title %}
    <link rel="stylesheet" type="text/css" href="{% static 'advito/css/style.css' %}">
</head>
<body>

<header>
<nav class="container header-nav">
        <ul class="header-nav">
            <li class="link-menu name">
                <a href="{% url 'index' %}">Meschat</a>
            </li>
            <li class="linked link-menu link-me">
                <a href="{% url 'people' %}">Пользователи</a>
            </li>
{#            {% if user.is_authenticated %}#}
{#            <li class="linked link-menu link-me">#}
{#                <a href="{% url 'dialogs' %}">Диалоги</a>#}
{#            </li>#}
{#            {% endif %}#}
        <li class="link-menu">
                <a class="linked" href="{% url 'category' %}">Категории</a>
            </li>
        {% if user.is_authenticated %}
            <li class="link-menu">
                <a class="linked" href="{% url 'post_create' %}">Создать пост</a>
            </li>
            {% endif %}
        </ul>

                {% if user.is_authenticated %}
                <a class="linked link-menu link-me" href="{% url 'profile' user.id %}">{{ user.username }}</a>
                    <form class="link-menu link-me" action="{% url 'logout' %}" method="GET">
                        {% csrf_token %}
                        <button class="log" type="submit"> Logout </button>
                    </form>
                {% else %}
                    <a class="linked link-menu link-me" href="{% url 'login' %}"> Login </a>
                {% endif %}
    </nav>

</header>
<main>
    <section class="container">
    <div class="time">
        <div class="center">
            До следующего года:
            <p1 id="timer"></p1>
        </div>
    </div>

        {% block unique_content %}
        {% endblock unique_content %}
    </section>
</main>
<!-- подвал -->
      <footer class="footer">
         <div class="container foo">
            <div class="footer-block-wraper">
               <section class="footer-block">
                  <h4 class="h-nav-footer">Navigation</h4>
                  <hr class="line-footer">
                   <ul class="nav-footer-wrap">
            <li class="nav-footer">
                <a href="{% url 'index' %}">Advito</a>
            </li>
            <li class="nav-footer">
                <a href="{% url 'category' %}">Категории</a>
            </li>
            <li class="nav-footer">
                {% if user.is_authenticated %}
                <a href="{% url 'profile' user.id %}">Профиль</a>
                {% endif %}
            </li>
                       {% if user.is_authenticated %}
                   <li class="nav-footer">
                       <a href="{% url 'post_create' %}"> Создать пост </a>
                   </li>
                {% endif %}
        </ul>
               </section>
               <section class="footer-block">
                  <h4 class="h-nav-footer">Customer Information</h4>
                  <hr class="line-footer">
                  <ul class="nav-footer-wrap">
                     <li class="nav-footer"><a href="#">Contact Us</a></li>
                     <li class="nav-footer"><a href="#">Sale Exclusions</a></li>
                     <li class="nav-footer"><a href="#">Shipping & Returns</a></li>
                     <li class="nav-footer"><a href="#">Terms & Conditions</a></li>
                     <li class="nav-footer"><a href="#">Privacy Policy</a></li>
                     <li class="nav-footer"><a href="#">Search</a></li>
                  </ul>
               </section>
               <section class="footer-block">
                  <h4 class="h-nav-footer">Connect</h4>
                  <hr class="line-footer">
                  <input name="a" placeholder="Email" class="pole">
                  <input type="submit" class="btnms" value="JOIN">
               </section>
            </div>
            <hr class="line-footer line-footer-bottom">
            <ul class="rat-wrap">
               <li class="rat bottom-link star" style="margin-left: 0;">
                  Company Rating
               <div class="rating-area">
                  <input type="radio" id="star-5" name="rating" value="5">
                  <label for="star-5" title="Оценка «5»"></label>
                  <input type="radio" id="star-4" name="rating" value="4">
                  <label for="star-4" title="Оценка «4»"></label>
                  <input type="radio" id="star-3" name="rating" value="3">
                  <label for="star-3" title="Оценка «3»"></label>
                  <input type="radio" id="star-2" name="rating" value="2">
                  <label for="star-2" title="Оценка «2»"></label>
                  <input type="radio" id="star-1" name="rating" value="1">
                  <label for="star-1" title="Оценка «1»"></label>
               </div>
               </li>
               <li class="rat">
                  Copyright © 2020 • Advito
               </li>
               <li class="rat bottom-link web-rat">
                  Web Design — Kto-to
               </li>
            </ul>
         </div>
      </footer>

</body>
<script src="{% static 'advito/script/timer.js' %}"></script>
</html>

advito-main/advito/templates/advito/people.html
{% extends 'advito/layout.html' %}
{% block unique_content %}
    <p>Пользователи</p>
{% for user in users %}
           <li class="post-set-block">
               <a href="{% url 'profile' user.user_id %}">
                   <p>{{ user.user }}</p>
               </a>
           </li>
           {% endfor %}

{% endblock unique_content %}

advito-main/advito/templates/advito/post-detail.html
{% extends 'advito/layout.html' %}
{% block unique_content %}
    {% if post %}
    <div class="post-detail">
        <img class="imagi left" alt="post image" src="{{ post.image.url }}"
             style="width:250px; height: 250px;">
        <div class="right">
        <p>Автор: <a class="underl" href= '{% url 'profile' post.author.id%}'> {{post.author.username}} </a></p>
        <a class="underl" href="{% url 'categ' post.category.id %}">{{ post.category.name }}</a>
        <p>{{ post.header }}</p>
        <p>Описание: {{ post.description }}</p>
        <p class="data">{{ post.date_pub }}</p>
    {% csrf_token %}
    {% if post.author == user %}
            <a class='red-post' href='{% url 'post_edit' post.id %}'> Редактировать пост </a>
    {% endif %}
        </div>
    </div>
{#        <h1> Комментарии </h1>#}
{#            {% if comments.all %}#}
{#            {% for comment in comments.all %}#}
{#            <hr>#}
{#                <h3> <b> {{ comment.author.username }} </b> : {{comment.text}} </h3>#}
{#                <p> {{comment.date_publish|date:"d F G:i" }} </p>#}
{#            {% endfor %}#}
{#            {% else %}#}
{#                <h3> Комментариев нет. Вы можете стать первым. </h3>#}
{#            {% endif %}#}
{#            <hr>#}
{#            {% if comment_form %}#}
{#                <form method='POST'>#}
{#                    <p> Комментарий:#}
{#                    {% csrf_token %} {{comment_form.text}} </p>#}
{#                <button type='submit'> Отправить </button>#}
{#                </form>#}
{#            {% else %}#}
{#                <p> Комментарии только для зарегистрированных пользователей </p>#}
{#            {% endif %}#}
    {% endif %}
{% endblock unique_content %}

advito-main/advito/templates/advito/post_create.html
{% extends 'advito/layout.html' %}
{% block unique_content %}
    {% if user.is_authenticated %}
    <form enctype="multipart/form-data" method="post">
        {% csrf_token %}
        <div class="form">
            {{ form.as_p }}
        </div>
        <button class="publih" type="submit">Опубликовать</button>
    </form>
    {% else %}
    <p>Создавать посты могут только зарегистрированные пользователи</p>
    {% endif %}
{% endblock unique_content %}

advito-main/advito/templates/advito/post_delete.html
{% extends 'advito/layout.html' %}
{% block unique_content %}
    {% if post.author != user %}
    <h1 class='msg'> Удалить данный пост может только его автор </h2>
{% else %}
    <h1 class='msg'> Вы уверены, что хотите удалить этот пост? </h1>
        <div class='container text-center'>
            <div class="btn-group text-center" role="group">
                <form method='post' action='{% url 'post_delete' post.id %}'>
                    {% csrf_token %} <button type='submit' class='btn btn-danger'> Удалить </button>
                </form>
                <a href="{% url 'post_detail' post.id %}" class='btn btn-info'>  Нет </a>
            </div>
        </div>
{% endif %}
{% endblock unique_content %}

advito-main/advito/templates/advito/post_edit.html
{% extends 'advito/layout.html' %}
{% block unique_content %}
    <form method="post" enctype="multipart/form-data">{% csrf_token %}
        <div class="form">
            {{ form.as_p }}
        </div>
    <button type="submit" class="publih ptin" > Принять изменения </button>
    </form>
    <form action ='{% url 'post_delete' add.id %}' method="get">
        {% csrf_token %}
            <button class="publih delete" type="submit"> Удалить пост </button>
    </form>
{% if post.author == user %}
{% endif %}
{% endblock unique_content %}

advito-main/advito/templates/advito/profile.html
{% extends 'advito/layout.html' %}
{% block title %}
        <title>{{ profile.user.username }}</title>
    {% endblock title %}
{% block unique_content %}
    <section class="proile-view">
    {% if profile.ava %}
    <div class="left">
        <img class="ava" style="    width: 260px; height: 220px;" src= '{{ profile.ava.url }}'/>
    </div>
    {% endif %}
    <div class="right">
            <p class='nickname'> {{ profile.user.username }} </p>
            <p> Дата рождения:
            {% if profile.birth_date %}
                <i> {{ profile.birth_date|date:"d F Y" }} </i>
                {% else %}
                <i>Не указано</i>
            {% endif %}
            </p>
            <p>Телефон:
            {% if profile.phone_number %}
                <a href="tel:{{ profile.phone_number }}">{{ profile.phone_number }}</a>
            {% endif%}</p>
            <p> Обо мне:
            {% if profile.about %}
                <i> {{ profile.about }} </i>
            {% endif %}
            </p>
            {% if user.id == profile.user.id %}
                <a href="{% url 'edit-profile' profile.user.id %}" >  Редактировать профиль  </a>
            {% endif %}
    </div>
    </section>
    <section class="post-content">
        {% if profile.user.add_set.all  %}
        <hr class="line-prof">
        <p style="margin-bottom: 30px;">
        Посты {{ profile.user.username }}
        </p>
            <div class="posts">

        <!-- Элементы с постами -->
                {% for post in profile.user.add_set.all %}
                   <div class="post-user">
                       <a href="{% url 'post_detail' post.id %}">
                           <div class="right">
                                <img class="imagi" alt="post image" src="{{ post.image.url }}"
                                     style="width:200px; height: 200px;">
                                <p class="data-min">{{ post.date_pub }}</p>
                                       </div>
                                <div class="right left">
                                <p>Автор: <a class="underl" href= '{% url 'profile' post.author.id%}'> {{post.author.username}} </a></p>
                                <a class="underl" href="{% url 'categ' post.category.id %}">{{ post.category.name }}</a>
                                <p>{{ post.header }}</p>
                                <p>Описание: {{ post.description }}</p>
                            {% csrf_token %}
                            {% if post.author == user %}
                                    <a class='red-post' href='{% url 'post_edit' post.id %}'> Редактировать </a>
                            {% endif %}
                        </div>
                       </a>
                </div>
                {% endfor %}
        <!-- Конец элементов с постами -->
        {% else %}
                <a> Постов нет. </a>
        {% endif %}
            </div>
    </section>

{% endblock unique_content %}